import fs from 'node:fs'
import path from 'node:path'
import type { FrameworkId, ProjectModel } from '../core/types.js'
import { detectProject } from '../detect/project.js'

export interface StarterConfig {
  extends: 'ci'
  fail_on: 'high'
  require?: { typecheck: boolean }
  protected_areas?: string[]
}

export interface Detection {
  label: string
}

const FRAMEWORK_LABEL: Record<FrameworkId, string> = {
  node: 'Node.js',
  express: 'Express',
  fastify: 'Fastify',
  hono: 'Hono',
  nestjs: 'NestJS',
  react: 'React',
  vite: 'Vite',
  nextjs: 'Next.js',
  remix: 'Remix',
  astro: 'Astro',
  nuxt: 'Nuxt',
  vue: 'Vue',
  sveltekit: 'SvelteKit',
  angular: 'Angular',
}

function displayFrameworks(ids: FrameworkId[]): FrameworkId[] {
  const set = new Set(ids.filter((id) => id !== 'node'))
  if (
    set.has('nextjs') ||
    set.has('remix') ||
    set.has('nuxt') ||
    set.has('angular') ||
    set.has('sveltekit') ||
    set.has('astro')
  ) {
    set.delete('react')
    set.delete('vue')
    set.delete('vite')
  }
  return [...set]
}

const PROTECTED_MARKERS: Array<{ glob: string; markers: string[] }> = [
  { glob: 'src/auth/**', markers: ['src/auth'] },
  { glob: 'src/payments/**', markers: ['src/payments'] },
  { glob: 'src/billing/**', markers: ['src/billing'] },
  { glob: 'src/lib/auth/**', markers: ['src/lib/auth'] },
  { glob: 'prisma/migrations/**', markers: ['prisma/migrations'] },
  { glob: 'drizzle/**', markers: ['drizzle'] },
  { glob: 'src/app/api/**', markers: ['src/app/api'] },
  { glob: 'app/api/**', markers: ['app/api'] },
  { glob: 'src/pages/api/**', markers: ['src/pages/api'] },
  { glob: 'pages/api/**', markers: ['pages/api'] },
  { glob: 'src/middleware.ts', markers: ['src/middleware.ts'] },
  { glob: 'middleware.ts', markers: ['middleware.ts'] },
]

export function collectDetections(project: ProjectModel): Detection[] {
  const detections: Detection[] = [{ label: 'Node.js' }]

  if (project.language === 'typescript') detections.push({ label: 'TypeScript' })
  else if (project.language === 'javascript') detections.push({ label: 'JavaScript' })
  else detections.push({ label: 'TypeScript/JavaScript' })

  const frameworks = displayFrameworks(project.frameworks)
  for (const id of frameworks) {
    detections.push({ label: FRAMEWORK_LABEL[id] })
  }

  detections.push({
    label: project.packageManager === 'yarn' ? 'Yarn' : project.packageManager,
  })

  if (project.lint.tool === 'eslint') detections.push({ label: 'ESLint' })
  if (project.lint.tool === 'biome') detections.push({ label: 'Biome' })

  if (project.test.runner === 'vitest') detections.push({ label: 'Vitest' })
  else if (project.test.runner === 'jest') detections.push({ label: 'Jest' })
  else if (project.test.runner === 'node') detections.push({ label: 'Node.js test runner' })

  if (project.orm === 'prisma') detections.push({ label: 'Prisma' })
  if (project.orm === 'drizzle') detections.push({ label: 'Drizzle' })
  if (project.orm === 'typeorm') detections.push({ label: 'TypeORM' })

  if (project.monorepo.kind !== 'none') {
    detections.push({ label: `${project.monorepo.kind} workspace` })
  }

  return detections
}

export function detectProtectedAreas(root: string): string[] {
  const areas: string[] = []
  for (const { glob, markers } of PROTECTED_MARKERS) {
    if (markers.some((marker) => fs.existsSync(path.join(root, marker)))) {
      areas.push(glob)
    }
  }
  return areas
}

export function buildStarterConfig(project: ProjectModel): StarterConfig {
  const config: StarterConfig = {
    extends: 'ci',
    fail_on: 'high',
  }

  const typescript = project.language === 'typescript' || project.language === 'mixed'
  if (!typescript) {
    config.require = { typecheck: false }
  }

  const protectedAreas = detectProtectedAreas(project.root)
  if (protectedAreas.length > 0) {
    config.protected_areas = protectedAreas
  }

  return config
}

export function preferredConfigFileName(project: ProjectModel): string {
  return project.language === 'javascript'
    ? 'agentproof.config.yaml'
    : 'agentproof.config.ts'
}

export function formatStarterConfig(
  config: StarterConfig,
  format: 'ts' | 'yaml' | 'json' | 'js',
): string {
  if (format === 'json') {
    return `${JSON.stringify(config, null, 2)}\n`
  }
  if (format === 'ts' || format === 'js') {
    const body = JSON.stringify(config, null, 2)
    const header =
      format === 'ts'
        ? '/** Generated by `agentproof init`. */\n'
        : '/* Generated by `agentproof init`. */\n'
    return `${header}export default ${body}\n`
  }
  return formatYaml(config)
}

export function formatFromFileName(fileName: string): 'ts' | 'yaml' | 'json' | 'js' {
  if (fileName.endsWith('.json')) return 'json'
  if (fileName.endsWith('.js') || fileName.endsWith('.mjs')) return 'js'
  if (fileName.endsWith('.ts')) return 'ts'
  return 'yaml'
}

function formatYaml(config: StarterConfig): string {
  const lines = [
    '# Generated by `agentproof init`.',
    `extends: ${config.extends}`,
    `fail_on: ${config.fail_on}`,
  ]
  if (config.require) {
    lines.push('', 'require:')
    lines.push(`  typecheck: ${config.require.typecheck}`)
  }
  if (config.protected_areas && config.protected_areas.length > 0) {
    lines.push('', 'protected_areas:')
    for (const glob of config.protected_areas) {
      lines.push(`  - "${glob}"`)
    }
  }
  lines.push('')
  return lines.join('\n')
}

export function inspectForInit(cwd: string): {
  project: ProjectModel
  detections: Detection[]
  config: StarterConfig
  preferredFileName: string
} {
  const project = detectProject(cwd)
  return {
    project,
    detections: collectDetections(project),
    config: buildStarterConfig(project),
    preferredFileName: preferredConfigFileName(project),
  }
}
